import:
- complex
- multi_lookup_embedder
- AdaE
complex:
  entity_embedder:
    type: multi_lookup_embedder
    dropout: 0.3592749142853321
    regularize_weight: 4.5230047706178325e-06
    # pretrain:
    #   model_filename: 'local/wnrr/experiments/20231128-141408-complex-80-0.5255808623927111-1vsAll-reciprocal_relations_model/checkpoint_best.pt'
  relation_embedder:
    type: multi_lookup_embedder
    dropout: 0.3112283826796357
    regularize_weight: 4.192985917075565e-10
    # pretrain:
    #   model_filename: 'local/wnrr/experiments/20231128-141408-complex-80-0.5255808623927111-1vsAll-reciprocal_relations_model/checkpoint_best.pt'
dataset:
  name: wnrr
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example


multi_lookup_embedder:
  dim: 80
  initialize: uniform_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.0005472140383629246
    uniform_:
      a: -0.28148249060722197
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
model: AdaE
negative_sampling:
  implementation: batch
  num_samples:
    p: -1
AdaE:
  base_model:
    type: complex
train:
  auto_correct: true
  batch_size: 512
  loss_arg: 1.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 5
    threshold: 0.0001
  max_epochs: 40
  optimizer_args:
    lr: 0.523
  type: darts
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10
  every: 5



AdaE_config:
  adae: True
  bi-level: False
  share: True
  type: '1vsall'
  ali_way: 'zp'
  # train_mode: ['rank','auto','fix','original']
  train_mode: 'auto'
  cie: False
  padding: -0.28
  dim_list: [20,40,80,160]
  choice_list: [0.2]
  s_u: 3
  ratio: 0.8
  urolled: False
  t_s: 128
  lr_p: 0.001
  device: 'cuda:0'
  no_picker: False
  #目前device没用