KvsAll:
  label_smoothing: 0.07398311105554728
dataset:
  name: wnrr
distmult:
  entity_embedder:
    type: multi_lookup_embedder 
    dropout: 0.3667933782666931
    regularize_weight: 2.504743872791287e-12
  relation_embedder:
    type: multi_lookup_embedder
    dropout: 0.5
    regularize_weight: 3.0597172820406116e-14
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example
import:
- distmult
- multi_lookup_embedder
- AdaE
multi_lookup_embedder:
  dim: 512
  initialize: uniform_
  initialize_args:
    normal_:
      mean: 0.0
      std: 1.0
    uniform_:
      a: -0.7226369686094678
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize_args:
    p: 3
    weighted: true
model: AdaE
negative_sampling:
  implementation: batch
  num_samples:
    p: -1
AdaE:
  base_model:
    type: distmult
train:
  auto_correct: true
  batch_size: 1024
  loss_arg: 1.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 7
    threshold: 0.0001
  max_epochs: 400
  optimizer_args:
    lr: 0.3312683797847912
  type: darts
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10

AdaE_config:
  adae: True
  bi-level: False
  share: True
  type: 'kvsall'
  ali_way: 'zp'
  cie: True
  # train_mode: ['rank','auto','fix','original']
  train_mode: 'auto'
  dim_list: [1,128]
  choice_list: [-1]
  s_u: 2
  ratio: 0.8
  urolled: False
  t_s: 128
  lr_p: 0.1825
  device: 'cuda:0'
