dataset:
  name: wnrr
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example
import:
- transe
- AdaE
- multi_lookup_embedder
- reciprocal_relations_model
multi_lookup_embedder:
  dim: 256
  initialize: xavier_normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.00036174939032954854
    uniform_:
      a: -0.393658811201549
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
model: AdaE
negative_sampling:
  num_samples:
    o: 158
    p: -1
    s: 70
AdaE:
  base_model:
    type: transe
train:
  auto_correct: true
  batch_size: 128
  loss_arg: 1.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 5
    threshold: 0.0001
  max_epochs: 200
  optimizer_args:
    lr: 0.25
  type: darts
transe:
  entity_embedder:
    type: multi_lookup_embedder
    dropout: 0.2519204934424376
    normalize:
      p: -1.0
    regularize_weight: 2.1299293567133326e-07
    pretrain:
      model_filename: '/home/guanzp/code/AdaE/kge/local/wnrr/experiments/20231109-163639-transe-512-0.2532720169185861-KvsAll-reciprocal_relations_model/checkpoint_best.pt'
  l_norm: 2.0
  relation_embedder:
    type: multi_lookup_embedder
    dropout: -0.025948206777731686
    normalize:
      p: -1.0
    regularize_weight: 8.992034045083661e-13
    pretrain:
      model_filename: '/home/guanzp/code/AdaE/kge/local/wnrr/experiments/20231109-163639-transe-512-0.2532720169185861-KvsAll-reciprocal_relations_model/checkpoint_best.pt'
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10
AdaE_config:
  adae: True
  bi-level: False
  share: True
  type: '1vsall'
  ali_way: 'zp'
  cie: True
  # train_mode: ['rank','auto','fix','original']
  train_mode: 'auto'
  dim_list: [1,256]
  choice_list: [-1]
  s_u: 2
  ratio: 0.5
  urolled: False
  t_s: 512
  lr_p: 0.1825
  device: 'cuda:1'
  #目前device没用