job.type: train
dataset.name: fb15k-237

model: transe

   

train:
  type: negative_sampling
  batch_size: 128
  loss: margin_ranking
  
  max_epochs: 400
  optimizer.default:
    type: Adagrad
    args:
      lr:  0.04122

valid:
  early_stopping.patience: 5
  every: 5
  metric: mean_reciprocal_rank_filtered_with_test

eval:
  batch_size: 512

negative_sampling:
  num_samples.s: 2  # default: p=0; o=s
  num_samples.o: 56
  sampling_type: uniform

lookup_embedder:
  dim: 512
  regularize: lp
  regularize_args:
    p: 2
    weighted: False
  initialize:  xavier_normal_

transe:
  l_norm: 1.
  entity_embedder:
    type: lookup_embedder
    regularize_weight: 1.32e-07
  relation_embedder:
    type: lookup_embedder
    regularize_weight: 3.72e-18



