conve:
  entity_embedder:
    type: multi_lookup_embedder
    dropout: 0.3
    regularize_weight: 8.605027799155396e-15
    # pretrain:
    #  model_filename: "/home/guanzp/code/AdaE/kge/local/fb15k-237/experiments/20240115-044449-conve/checkpoint_best.pt"
  feature_map_dropout: 0.48769345636955713
  projection_dropout: 0.5
  relation_embedder:
    type: multi_lookup_embedder
    dropout: 0.11757230155305998
    regularize_weight: 2.231687936571624e-14
    # pretrain:
    #  model_filename: "/home/guanzp/code/AdaE/kge/local/fb15k-237/experiments/20240115-044449-conve/checkpoint_best.pt"
  round_dim: true
dataset:
  name: fb15k-237
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example
import:
- conve
- AdaE
- multi_lookup_embedder
- reciprocal_relations_model
multi_lookup_embedder:
  dim: 256
  initialize: xavier_normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 2.568825067721716e-05
    uniform_:
      a: -0.43447215763614
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize_args:
    p: 3
    weighted: true
model: AdaE
negative_sampling:
  implementation: batch
  num_samples:
    p: -1
AdaE:
  base_model:
    type: conve
train:
  auto_correct: true
  batch_size: 1024
  loss_arg: 1.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 9
    threshold: 0.0001
  max_epochs: 400
  optimizer_args:
    lr: 0.05
  type: darts
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10
AdaE_config:
  adae: True
  bi-level: False
  share: False
  type: '1vsall'
  ali_way: 'zp'
  cie: False
  # train_mode: ['rank','auto','fix','original']
  train_mode: 'auto'
  dim_list: [64,128,256,512,768]
  choice_list: [-1]
  s_u: 2
  ratio: 0.8
  urolled: False
  t_s: 512
  lr_p: 0.01
  device: 'cuda:0'
  #目前device没用